# Generated by Django 2.2.6 on 2019-10-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('className', models.CharField(max_length=150)),
                ('isDelete', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'schoolink_classes',
            },
        ),
    ]
