# Generated by Django 2.2.6 on 2019-10-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
