# Generated by Django 2.2.6 on 2019-10-29 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_classes_deleted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('isDelete', models.CharField(max_length=10)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Classes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
