# Generated by Django 2.2.6 on 2019-10-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_sections'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sections',
            table='schoolink_sections',
        ),
    ]
