# Generated by Django 2.2.6 on 2019-10-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191029_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Classes'),
        ),
    ]
