# Generated by Django 2.2.6 on 2019-10-21 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcm_id', models.IntegerField()),
                ('fname', models.CharField(max_length=255)),
                ('deviceType', models.CharField(max_length=150)),
                ('active', models.IntegerField(default=0)),
                ('userType', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rememberToken', models.TextField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 10, 21, 11, 8, 11, 219735))),
                ('isDelete', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'schoolink_user',
            },
        ),
    ]
