# Generated by Django 2.2.6 on 2019-10-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191021_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gcm_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='isDelete',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
